import { useState } from 'react'
import type { Suggestion, SuggestionChoice, SuggestionState } from '../types'
import { AlertIcon, RetryIcon, SparkleIcon } from './icons'

type SuggestionPanelProps = {
  state: SuggestionState
  onAccept: (choice: SuggestionChoice) => void
  onDismiss: () => void
  onRetry: () => void
}

// 32px min height keeps panel buttons comfortable touch targets. The hover fill
// is surface-raised so it shows on every panel background (muted, accent, danger).
const button =
  'flex min-h-8 items-center gap-1 rounded-md px-2.5 text-xs font-medium transition-colors'
const ghostButton = `${button} text-fg-muted hover:bg-surface-raised hover:text-fg`
const primaryButton = `${button} cursor-pointer bg-accent text-accent-fg hover:bg-accent-hover`
const secondaryButton = `${button} cursor-pointer border border-border-strong bg-surface-raised text-fg hover:bg-surface-muted`

// Hovering or focusing a "Use…" button outlines the part it would keep. The
// padding is always there (offset by negative margin) so the outline doesn't shift layout.
const previewTarget = '-mx-1.5 rounded-sm px-1.5 py-0.5 transition-shadow'
const previewOn = 'bg-surface-raised ring-2 ring-accent'

type ReadySuggestionProps = {
  suggestion: Suggestion
  onAccept: (choice: SuggestionChoice) => void
  onDismiss: () => void
}

function ReadySuggestion({ suggestion, onAccept, onDismiss }: ReadySuggestionProps) {
  const { improvedName, tips, category, model } = suggestion
  const hasTips = tips.length > 0
  // Hover and focus are tracked apart, so moving the mouse away doesn't clear a keyboard preview.
  const [hovered, setHovered] = useState<SuggestionChoice | null>(null)
  const [focused, setFocused] = useState<SuggestionChoice | null>(null)
  const preview = hovered ?? focused

  function choiceButton(choice: SuggestionChoice, label: string, className: string) {
    return (
      <button
        type="button"
        onClick={() => onAccept(choice)}
        onMouseEnter={() => setHovered(choice)}
        onMouseLeave={() => setHovered(null)}
        onFocus={() => setFocused(choice)}
        onBlur={() => setFocused(null)}
        className={className}
      >
        {label}
      </button>
    )
  }

  return (
    <section
      aria-label="AI suggestion"
      className="flex flex-col gap-2 rounded-md border border-border bg-accent-subtle p-3"
    >
      <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
        <SparkleIcon className="size-3.5 text-accent-text" />
        <span className="text-xs font-medium text-accent-text">AI suggestion</span>
        {/* Attribution: which model wrote this. Older saved suggestions have no model. */}
        <span className="min-w-0 text-xs break-words text-fg-muted">
          {model ? `Generated by ${model}` : 'Generated by AI'}
        </span>
        {category && (
          // The category is kept with every choice, so it's outlined for all of them.
          <span
            className={`rounded-sm bg-surface-raised px-1.5 py-0.5 text-xs text-fg-muted transition-shadow ${
              preview ? 'ring-1 ring-accent' : ''
            }`}
          >
            {category}
          </span>
        )}
      </div>
      {/* Name and tips share a wrapper so "Use both" outlines them as one block. */}
      <div
        data-previewing={preview === 'both' || undefined}
        className={`flex flex-col gap-2 ${previewTarget} ${preview === 'both' ? previewOn : ''}`}
      >
        <p
          data-previewing={preview === 'name' || undefined}
          className={`text-sm font-medium break-words text-fg ${previewTarget} ${
            preview === 'name' ? previewOn : ''
          }`}
        >
          {improvedName}
        </p>
        {hasTips && (
          <div
            data-previewing={preview === 'tips' || undefined}
            className={`${previewTarget} ${preview === 'tips' ? previewOn : ''}`}
          >
            <ul className="flex list-disc flex-col gap-1 pl-4 text-xs text-fg-muted marker:text-fg-subtle">
              {tips.map((tip, index) => (
                <li key={index}>{tip}</li>
              ))}
            </ul>
          </div>
        )}
      </div>
      <div className="flex flex-wrap gap-2 pt-1">
        {/* The fullest option is the primary action. Without tips, that's the name. */}
        {choiceButton('name', 'Use this name', hasTips ? secondaryButton : primaryButton)}
        {hasTips && choiceButton('tips', 'Use these tips', secondaryButton)}
        {hasTips && choiceButton('both', 'Use both', primaryButton)}
        <button type="button" onClick={onDismiss} className={ghostButton}>
          Dismiss
        </button>
      </div>
    </section>
  )
}

// Inline panel rendered below a TaskItem, indented to line up with the task name.
function SuggestionPanel({ state, onAccept, onDismiss, onRetry }: SuggestionPanelProps) {
  switch (state.status) {
    case 'loading':
      return (
        <div
          role="status"
          className="rounded-md border border-border bg-surface-raised p-3"
        >
          <span className="sr-only">Getting a suggestion…</span>
          <div aria-hidden="true" className="flex animate-pulse flex-col gap-2 motion-reduce:animate-none">
            <div className="h-3 w-16 rounded-sm bg-border" />
            <div className="h-4 w-3/4 rounded-sm bg-border" />
            <div className="h-3 w-full rounded-sm bg-border" />
            <div className="h-3 w-2/3 rounded-sm bg-border" />
          </div>
        </div>
      )

    case 'ready':
      return (
        <ReadySuggestion suggestion={state.suggestion} onAccept={onAccept} onDismiss={onDismiss} />
      )

    case 'empty':
      return (
        <div
          role="status"
          className="flex flex-col items-start gap-1 rounded-md border border-border bg-surface-muted py-2 pr-2 pl-3 sm:flex-row sm:items-center sm:justify-between sm:gap-3"
        >
          <p className="text-xs text-fg-muted">No suggestion for this one. Try adding more detail.</p>
          <button type="button" onClick={onDismiss} className={`${ghostButton} -ml-2.5 sm:ml-0`}>
            Dismiss
          </button>
        </div>
      )

    case 'error':
      return (
        <div
          role="alert"
          className="flex flex-col gap-1 rounded-md border border-danger/30 bg-danger-subtle py-2 pr-2 pl-3 sm:flex-row sm:items-center sm:gap-2"
        >
          <div className="flex flex-1 items-start gap-2">
            <AlertIcon className="size-4 shrink-0 text-danger" />
            <p className="text-xs text-fg">Couldn’t get a suggestion. Please try again.</p>
          </div>
          {/* On narrow screens the actions wrap under the message, aligned with its text. */}
          <div className="flex gap-1 pl-3.5 sm:pl-0">
            <button
              type="button"
              onClick={onRetry}
              className={`${button} text-danger hover:bg-surface-raised`}
            >
              <RetryIcon className="size-3.5" />
              Retry
            </button>
            <button type="button" onClick={onDismiss} className={ghostButton}>
              Dismiss
            </button>
          </div>
        </div>
      )
  }
}

export default SuggestionPanel
