import { useState } from 'react'
import type { Suggestion, SuggestionState } from '../types'
import { AlertIcon, RetryIcon, SparkleIcon } from './icons'

type SuggestionPanelProps = {
  state: SuggestionState
  onAccept: (improvedName: string) => void
  onDismiss: () => void
  onRetry: () => void
}

// 32px min height keeps panel buttons comfortable touch targets. The hover fill
// is surface-raised so it shows on every panel background (muted, accent, danger).
const button =
  'flex min-h-8 items-center gap-1 rounded-md px-2.5 text-xs font-medium transition-colors'
const ghostButton = `${button} text-fg-muted hover:bg-surface-raised hover:text-fg`

type ReadySuggestionProps = {
  suggestion: Suggestion
  onAccept: (improvedName: string) => void
  onDismiss: () => void
}

function ReadySuggestion({ suggestion, onAccept, onDismiss }: ReadySuggestionProps) {
  const { improvedName, tips, category, model } = suggestion
  // While "Use this name" is hovered or focused, highlight the name it will apply.
  const [previewing, setPreviewing] = useState(false)
  const preview = () => setPreviewing(true)
  const endPreview = () => setPreviewing(false)

  return (
    <section
      aria-label="AI suggestion"
      className="flex flex-col gap-2 rounded-md border border-border bg-accent-subtle p-3"
    >
      <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
        <SparkleIcon className="size-3.5 text-accent-text" />
        <span className="text-xs font-medium text-accent-text">AI suggestion</span>
        {category && (
          <span className="rounded-sm bg-surface-raised px-1.5 py-0.5 text-xs text-fg-muted">
            {category}
          </span>
        )}
        {/* Attribution: which model wrote this. Older saved suggestions have no model. */}
        <span className="min-w-0 text-xs break-words text-fg-muted">
          {model ? `Generated by ${model}` : 'Generated by AI'}
        </span>
      </div>
      <p
        data-previewing={previewing || undefined}
        className={`-mx-1 rounded-sm px-1 text-sm font-medium break-words text-fg transition-colors ${
          previewing ? 'bg-surface-raised ring-2 ring-accent' : ''
        }`}
      >
        {improvedName}
      </p>
      {tips.length > 0 && (
        <ul className="flex list-disc flex-col gap-1 pl-4 text-xs text-fg-muted marker:text-fg-subtle">
          {tips.map((tip, index) => (
            <li key={index}>{tip}</li>
          ))}
        </ul>
      )}
      <div className="flex gap-2 pt-1">
        <button
          type="button"
          onClick={() => onAccept(improvedName)}
          onMouseEnter={preview}
          onMouseLeave={endPreview}
          onFocus={preview}
          onBlur={endPreview}
          className={`${button} bg-accent text-accent-fg hover:bg-accent-hover`}
        >
          Use this name
        </button>
        <button type="button" onClick={onDismiss} className={ghostButton}>
          Dismiss
        </button>
      </div>
    </section>
  )
}

// Inline panel rendered below a TaskItem, indented to line up with the task name.
function SuggestionPanel({ state, onAccept, onDismiss, onRetry }: SuggestionPanelProps) {
  switch (state.status) {
    case 'loading':
      return (
        <div
          role="status"
          className="rounded-md border border-border bg-surface-raised p-3"
        >
          <span className="sr-only">Getting a suggestion…</span>
          <div aria-hidden="true" className="flex animate-pulse flex-col gap-2 motion-reduce:animate-none">
            <div className="h-3 w-16 rounded-sm bg-border" />
            <div className="h-4 w-3/4 rounded-sm bg-border" />
            <div className="h-3 w-full rounded-sm bg-border" />
            <div className="h-3 w-2/3 rounded-sm bg-border" />
          </div>
        </div>
      )

    case 'ready':
      return (
        <ReadySuggestion suggestion={state.suggestion} onAccept={onAccept} onDismiss={onDismiss} />
      )

    case 'empty':
      return (
        <div
          role="status"
          className="flex flex-col items-start gap-1 rounded-md border border-border bg-surface-muted py-2 pr-2 pl-3 sm:flex-row sm:items-center sm:justify-between sm:gap-3"
        >
          <p className="text-xs text-fg-muted">No suggestion for this one. Try adding more detail.</p>
          <button type="button" onClick={onDismiss} className={`${ghostButton} -ml-2.5 sm:ml-0`}>
            Dismiss
          </button>
        </div>
      )

    case 'error':
      return (
        <div
          role="alert"
          className="flex flex-col gap-1 rounded-md border border-danger/30 bg-danger-subtle py-2 pr-2 pl-3 sm:flex-row sm:items-center sm:gap-2"
        >
          <div className="flex flex-1 items-start gap-2">
            <AlertIcon className="size-4 shrink-0 text-danger" />
            <p className="text-xs text-fg">Couldn’t get a suggestion. Please try again.</p>
          </div>
          {/* On narrow screens the actions wrap under the message, aligned with its text. */}
          <div className="flex gap-1 pl-3.5 sm:pl-0">
            <button
              type="button"
              onClick={onRetry}
              className={`${button} text-danger hover:bg-surface-raised`}
            >
              <RetryIcon className="size-3.5" />
              Retry
            </button>
            <button type="button" onClick={onDismiss} className={ghostButton}>
              Dismiss
            </button>
          </div>
        </div>
      )
  }
}

export default SuggestionPanel
