import { useState } from 'react'
import type { ReactNode } from 'react'
import AddTaskForm from '../components/AddTaskForm'
import ConfirmDialog from '../components/ConfirmDialog'
import Header from '../components/Header'
import TaskList from '../components/TaskList'
import type { SuggestionState, Task } from '../types'

// Dev-only gallery of every TaskItem / TaskList state. Open http://localhost:5173/#states under `npm run dev`.
// Stripped from production builds (see main.tsx).

const noop = () => {}
const handlers = {
  onToggle: noop,
  onDelete: noop,
  onSuggest: noop,
  onAcceptSuggestion: noop,
  onDismissSuggestion: noop,
}

const examples: { title: string; note: string; task: Task; suggestion?: SuggestionState }[] = [
  {
    title: 'Default',
    note: 'Idle: no suggestion requested. Hover or focus the row to see the hover state.',
    task: { id: 'default', name: 'email landlord', done: false },
  },
  {
    title: 'Details: tips and created time',
    note: 'Details (always shown) animates open to the kept tips, with the created time dimmed at the bottom right in the user’s local time. Hover or focus Details, Improve or Delete for a tooltip; Escape hides it.',
    task: {
      id: 'created',
      name: 'Book dentist appointment',
      done: false,
      category: 'Health',
      tips: ['Check your calendar for a free morning', 'Have your insurance number ready'],
      createdAt: new Date(2026, 10, 9, 15, 45).toISOString(),
    },
  },
  {
    title: 'Details: created time only',
    note: 'With no kept tips, Details shows just the created time. Tasks saved before it was recorded say "Created: unknown".',
    task: {
      id: 'created-only',
      name: 'Water the plants',
      done: false,
      createdAt: new Date(2026, 8, 29, 8, 5).toISOString(),
    },
  },
  {
    title: 'Completed',
    note: 'Checked tasks are struck through, and the Improve action is hidden.',
    task: { id: 'done', name: 'Buy milk', done: true },
  },
  {
    title: 'Kept category and tips',
    note: 'After "Use both" or "Use these tips". The category sits next to the name; the Tips button expands the read-only list (collapsed by default).',
    task: {
      id: 'kept',
      name: 'Do a 30-minute strength workout at the gym',
      done: false,
      category: 'Health',
      tips: ['Pack your bag the night before', 'Pick a fixed time slot', 'Log your sets'],
    },
  },
  {
    title: 'Kept category only',
    note: 'After "Use this name": the category comes with the name, so Details has no tips (only the created time, here unknown).',
    task: { id: 'kept-name', name: 'Call Mum this evening', done: false, category: 'Personal' },
  },
  {
    title: 'Loading',
    note: 'The request is in flight. Improve ignores clicks (aria-disabled) to prevent duplicate submits but stays focusable.',
    task: { id: 'loading', name: 'plan trip', done: false },
    suggestion: { status: 'loading' },
  },
  {
    title: 'Suggestion',
    note: 'A 200 response, shown inline below the item and credited to its model. Hover or focus a "Use…" button to outline what it keeps.',
    task: { id: 'ready', name: 'gym', done: false },
    suggestion: {
      status: 'ready',
      suggestion: {
        improvedName: 'Do a 30-minute strength workout at the gym',
        tips: ['Pack your bag the night before', 'Pick a fixed time slot', 'Log your sets'],
        category: 'Health',
        model: 'gpt-4o-mini-2024-07-18',
      },
    },
  },
  {
    title: 'Suggestion without tips',
    note: 'The tips array can be empty, so only "Use this name" is offered. No model (a suggestion saved before models were recorded) falls back to "Generated by AI".',
    task: { id: 'no-tips', name: 'call mum', done: false },
    suggestion: {
      status: 'ready',
      suggestion: { improvedName: 'Call Mum this evening', tips: [], category: 'Personal' },
    },
  },
  {
    title: 'Suggestion with the same name',
    note: 'The suggested name matches the task’s (ignoring case and spacing), e.g. one the type-ahead filled in, so "Use this name" and "Use both" are hidden and only the tips are offered. With no tips either, "Use this category" keeps just the category.',
    task: { id: 'same-name', name: 'Book a dentist appointment', done: false },
    suggestion: {
      status: 'ready',
      suggestion: {
        improvedName: 'Book a dentist appointment',
        tips: ['Check your calendar for a free morning', 'Have your insurance number ready'],
        category: 'Health',
        model: 'gpt-6-luna',
      },
    },
  },
  {
    title: 'No suggestion',
    note: 'A 200 with a null body: the model refused or had nothing to offer.',
    task: { id: 'empty', name: 'x', done: false },
    suggestion: { status: 'empty' },
  },
  {
    title: 'Error',
    note: 'A 502 or network failure. Retry sends the request again.',
    task: { id: 'error', name: 'renew passport', done: false },
    suggestion: { status: 'error' },
  },
]

function Example({ title, note, children }: { title: string; note: string; children: ReactNode }) {
  return (
    <section className="flex flex-col gap-2">
      <div>
        <h2 className="text-sm font-semibold text-fg">{title}</h2>
        <p className="text-xs text-fg-muted">{note}</p>
      </div>
      {children}
    </section>
  )
}

function StatesPreview() {
  const [confirmOpen, setConfirmOpen] = useState(false)
  return (
    <div className="min-h-dvh">
      <Header />
      <main className="mx-auto flex w-full max-w-app flex-col gap-8 px-4 py-8">
        <p className="text-sm text-fg-muted">
          Component states preview (dev only). Toggle your OS theme to check dark mode.
        </p>
        <Example
          title="Type-ahead"
          note="With “Suggest as I type” on, a pause of about a second fetches a completion, shown as grey text after the caret. Tab accepts it, Escape dismisses it, Enter adds only what was typed. Touch screens get a ✓ button instead of Tab."
        >
          <AddTaskForm onAdd={noop} preview={{ name: 'Buy mi', completion: 'Buy milk and eggs' }} />
        </Example>
        {examples.map(({ title, note, task, suggestion }) => (
          <Example key={task.id} title={title} note={note}>
            <TaskList tasks={[task]} suggestions={{ [task.id]: suggestion }} {...handlers} />
          </Example>
        ))}
        <Example title="Empty list" note="Shown when there are no tasks.">
          <TaskList tasks={[]} onToggle={noop} onDelete={noop} />
        </Example>
        <Example
          title="Delete confirmation"
          note="Deleting an unfinished task asks first; completed tasks are deleted straight away. Cancel is focused, Escape cancels, and Tab stays inside."
        >
          <button
            type="button"
            onClick={() => setConfirmOpen(true)}
            className="min-h-8 self-start rounded-md border border-border-strong px-4 py-2 text-sm font-medium text-fg transition-colors hover:bg-surface-muted"
          >
            Open dialog
          </button>
        </Example>
      </main>
      {confirmOpen && (
        <ConfirmDialog
          title="Delete task?"
          confirmLabel="Delete"
          onConfirm={() => setConfirmOpen(false)}
          onCancel={() => setConfirmOpen(false)}
        >
          <p>“email landlord” isn’t done yet.</p>
          <p className="underline">This can’t be undone.</p>
        </ConfirmDialog>
      )}
    </div>
  )
}

export default StatesPreview
